services:
  - type: web
    name: ig-dm-app
    env: python
    buildCommand: ""
    startCommand: "python ig_dm_api_backend.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
    region: oregon
    autoDeploy: true
    env: python
